betodealmeida/shillelagh

- CHANGELOG.rst
- src/shillelagh/adapters/api/gsheets.py
- src/shillelagh/adapters/api/socrata.py
- src/shillelagh/adapters/api/weatherapi.py
- src/shillelagh/adapters/base.py
- src/shillelagh/backends/apsw/db.py
- src/shillelagh/backends/apsw/vt.py
- src/shillelagh/fields.py
- src/shillelagh/filters.py
- src/shillelagh/lib.py
- tests/adapters/api/test_gsheets.py
- tests/adapters/api/test_socrata.py
- tests/test_fields.py
- tests/test_lib.py
Writing this for myself...
There's a lot of type conversion — eg, converting a `datetime.datetime` to an ISO string — going on in `shillelagh`.
Adapters need to do type conversion in `get_data`, yielding native Python types. This means that the GSheets adapter needs to convert `Date(2020,0,1)` into `datetime.date(2020, 1, 1)` (months are zero-indexed!).
The `apsw` backend (`shillelagh.backends.apsw.vt`) needs to convert these values into types supported by SQLite. This means converting `datetime.date` back to an ISO string, eg. This is inefficient, but opens the door to more backends in the future (eg, https://multicorn.org/implementing-a-fdw/).
Finally, the `apsw` Python DB API 2 driver needs to convert the SQLite-safe types back to native types, so that the user gets `datetime.datetime` …
> feat: simplify type conversion

- src/shillelagh/adapters/base.py
- src/shillelagh/backends/apsw/vt.py
- src/shillelagh/fields.py
- tests/adapters/test_base.py
- tests/fakes/__init__.py
- tests/test_fields.py
This PR makes the `insert_row` and `update_row` methods in the adapter class compatible with the `get_rows` method. Just like `get_rows` expects rows with native Python types (`datetime`, eg), the DML functions should also receive native types. This means that the types need to be converted to the DB-native format before being passed to the adapter, in order to simplify the adapter.
> feat: improve type conversion

- src/shillelagh/filters.py
- src/shillelagh/lib.py
Add a `__repr__` to filters and fix a small bug in the row ID manager that should never happen.
> fix: row ID manager without rows

- src/shillelagh/adapters/api/gsheets.py
- src/shillelagh/adapters/base.py
- src/shillelagh/backends/apsw/db.py
- src/shillelagh/backends/apsw/vt.py
- src/shillelagh/fields.py
- tests/adapters/api/test_gsheets.py
- tests/test_fields.py
Add support for DML (`INSERT`, `UPDATE`, `DELETE`) in the Google Sheets adapter.
A few notes:
Deletions and updates are based on row ID. When a user runs `DELETE FROM table WHERE condition` the SQLite engine will run a `SELECT * FROM table WHERE condition` on the virtual table, and then use the returned row IDs to run a series of `DELETE FROM table WHERE rowid = ?`.
Ideally we'd use the row number as the row ID when returning data for a `SELECT`, but since it's not exposed in the Chart API we just return sequential numbers. To map those row IDs to the actual rows we store them in a `row_ids` dictionary after every `SELECT`. Then, on a delete or update we fetch the values for the row based on the row ID and delete the first row that matches (since SQL tables have no implicit ordering). …
> feat: DML for Google Sheets

- src/shillelagh/adapters/api/gsheets.py
- tests/adapters/api/test_gsheets.py
Introduce 2 additional sync modes for the Google Sheets adapter:
1. **Bidirectional** (current mode): all changes are pushed immediately, and the spreadsheet is downloaded before every `UPDATE`/`DELETE`. This is very inefficient, but prevent surprises and works good enough with small changes.
2. **Unidirectional**: all changes are pushed immediately, but the spreadsheet is downloaded only once before the first `UPDATE`/`DELETE`. This is at least 2x more efficient, since the state of the spreadsheet is downloaded only once — the bigger the spreadsheet the more efficient it becomes.
3. **Batch**: all changes are pushed at once when the connection closes, and the spreadsheet is downloaded before the first `UPDATE`/`DELETE`: This is the most efficient mode, requiring only 2 network calls, but …
> feat: Gsheets modes

- src/shillelagh/adapters/api/gsheets.py
- tests/adapters/api/test_gsheets.py
Make `get_data` read local data on `UNIDIRECTIONAL` and `BATCH` modes to make them consistent.
> feat: handle pending changes in GSheets

- .pre-commit-config.yaml
- CHANGELOG.rst
- src/shillelagh/adapters/api/gsheets.py
- src/shillelagh/adapters/base.py
- src/shillelagh/backends/apsw/db.py
- src/shillelagh/functions.py
- tests/adapters/api/test_gsheets.py
- tests/adapters/test_base.py
- tests/test_functions.py
Add 3 useful custom functions:
1. `sleep`, which sleeps for a number of seconds. This is useful for testing timeouts in queries.
2. `get_metadata`, which returns metadata about a given table.
3. `version`, to return the version of the installed Shillelagh.
> feat: add `sleep`, `version`, and `get_metadata` functions

- CHANGELOG.rst
- src/shillelagh/backends/apsw/db.py
- src/shillelagh/backends/apsw/dialects/base.py
- src/shillelagh/backends/apsw/dialects/gsheets.py
- src/shillelagh/backends/apsw/dialects/safe.py
- src/shillelagh/functions.py
- tests/backends/apsw/dialects/test_gsheets.py
- tests/backends/apsw/dialects/test_safe.py
- tests/backends/apsw/test_db.py
- tests/test_functions.py
Get rid of `adapter_args` in favor of using only `adapter_kwargs`.
> chore: remove `adapter_args`

- src/shillelagh/backends/apsw/db.py
- tests/backends/apsw/test_db.py
Addresses https://github.com/betodealmeida/shillelagh/issues/47.
It only works with the "main" schema.
> feat: strip schema prefix

- CHANGELOG.rst
- src/shillelagh/adapters/api/gsheets.py
- src/shillelagh/backends/apsw/dialects/base.py
- src/shillelagh/backends/apsw/dialects/gsheets.py
- src/shillelagh/backends/apsw/dialects/safe.py
- tests/adapters/api/test_gsheets.py
- tests/backends/apsw/dialects/test_gsheets.py
- tests/backends/apsw/dialects/test_safe.py
A catalog is just a map between a readable name and a sheet URL:
```python
connection = connect(
":memory:",
["gsheetsapi"],
adapter_kwargs={
"gsheetsapi": {
"catalog": {
"sheet": "https://docs.google.com/spreadsheets/d/1/edit#gid=0",
},
},
},
)
cursor = connection.cursor()
sql = "SELECT * FROM sheet"
data = list(cursor.execute(sql))
assert data == [
("BR", 1),
("BR", 3),
("IN", 5),
("ZA", 6),
("CR", 10),
]
```
> feat: support catalogs in GSheets

- src/shillelagh/adapters/api/gsheets/adapter.py
- src/shillelagh/adapters/api/gsheets/fields.py
- src/shillelagh/adapters/api/gsheets/lib.py
- src/shillelagh/adapters/api/socrata.py
- src/shillelagh/adapters/api/weatherapi.py
- src/shillelagh/backends/apsw/vt.py
- src/shillelagh/fields.py
- src/shillelagh/lib.py
- src/shillelagh/types.py
- src/shillelagh/typing.py
- tests/adapters/api/gsheets/test_adapter.py
- tests/adapters/api/gsheets/test_fields.py
- tests/adapters/api/gsheets/test_lib.py
- tests/adapters/file/test_csvfile.py
- tests/adapters/test_base.py
- tests/backends/apsw/test_db.py
- tests/backends/apsw/test_vt.py
- tests/fakes/__init__.py
- tests/test_fields.py
- tests/test_lib.py
Move the `Order` enum to `types.py` for consistency.
Closes https://github.com/betodealmeida/shillelagh/issues/58.
> chore: move enum to types for consistency

- src/shillelagh/backends/apsw/db.py
- src/shillelagh/exceptions.py
Import all exceptions in the `db` module.
> fix: have all exceptions in `db`

- CHANGELOG.rst
- src/shillelagh/adapters/api/gsheets/adapter.py
- src/shillelagh/adapters/api/gsheets/fields.py
- src/shillelagh/adapters/api/gsheets/lib.py
- src/shillelagh/adapters/api/weatherapi.py
- src/shillelagh/fields.py
- tests/adapters/api/gsheets/test_adapter.py
- tests/adapters/api/gsheets/test_fields.py
- tests/adapters/api/gsheets/test_lib.py
- tox.ini
This PR changes the GSheets adapter to use the formatted data, since it's common to the Chart and the Sheets APIs.
The Chart API returns timestamps like this:
```json
{"v": "Date(2021,6,7,17,14,33)", "f": "7/7/2021 17:14:33"}
```
Before, we were parsing the value from the `v` field.
We were using the unformatted data in the Sheets API, that looks like this for the same value:
```
44384.71844300038
```
The problem is that this value, when converted to a timestamp, is a few milliseconds off from "7/7/2021 17:14:33", preventing us from finding the row on a DML request.
The formatted data in the Sheets API, on the other hand, looks like this:
```
'7/7/2021 17:14:33'
```
I changed the Chart API to use the formatted value from the `f` field (when available), and the Sheets API to use the …
> fix: time/date and GSheets DML

- src/shillelagh/fields.py
- tests/adapters/api/gsheets/test_adapter.py
- tests/adapters/test_base.py
- tests/test_fields.py
When no timezone is specified, return a naive object.
Closes https://github.com/betodealmeida/shillelagh/issues/22.
> feat: return naive time objects by default

- CHANGELOG.rst
- README.rst
- docs/adapters.rst
- examples/csvfile.py
- examples/datasette.py
- src/shillelagh/adapters/api/datasette.py
- src/shillelagh/adapters/file/csvfile.py
- src/shillelagh/backends/apsw/db.py
- tests/adapters/api/test_datasette.py
- tests/adapters/file/test_csvfile.py
Remove the `csv://` and `datasette+` prefixes from URIs.
The URIs look cleaner, the only problem is that for Datasette we now require a `HEAD` request in `supports`, which slows down adapter resolution.
One option would be to implement a fine-grained `supports`, eg:
```python
MAYBE = None
@staticmethod
def supports(uri: str, fast: bool = True, **kwargs: Any) -> Optional[bool]:
parsed = urllib.parse.urlparse(uri)
if is_known_domain(parsed.netloc):
return True
if fast:
return MAYBE
return is_datasette(uri)
```
Then we can do a first pass on the adapters looking for `True`, and a second pass with `fast=False` on the ones that returned `MAYBE` on the first pass.
> feat: simplify uris

- src/shillelagh/console.py
Using SafeLoader instead of FullLoader to avoid security risks
here is a example proof of concept of arbitrary code execution using Fullloader :
using safeLoader will fix this 
**Hacktoberfest**
> [FIX] Security - useing Safeloader

- docs/adapters.rst
If all columns in a GSheet are string data, the spreadsheet might have difficulty determining which rows are header rows - see https://developers.google.com/chart/interactive/docs/spreadsheets#creating-a-chart-from-a-separate-spreadsheet
Add documentation detailing how to specify the number of header rows as part of the spreadsheet URI
> Add documentation details for GSheet header rows

- CHANGELOG.rst
- src/shillelagh/backends/apsw/db.py
- src/shillelagh/exceptions.py
- tests/backends/apsw/test_db.py
- tests/backends/apsw/test_dbapi.py
The library was not including the [type objects](https://www.python.org/dev/peps/pep-0249/#type-objects-and-constructors) in the `dbapi` module. Fixed and added unit tests to check for PEP 249 compliance.
> fix: PEP 249 compatibility

- docs/adapters.rst
- docs/usage.rst
There are a couple misspelled reference to the gsheetsapi adapter. 
`s/gsheetspi/gsheetsapi`
> fix doc typos

- AUTHORS.rst
- docs/adapters.rst
- src/shillelagh/adapters/api/gsheets/adapter.py
- src/shillelagh/adapters/api/gsheets/lib.py
- src/shillelagh/backends/apsw/dialects/gsheets.py
- tests/adapters/api/gsheets/test_adapter.py
- tests/adapters/api/gsheets/test_lib.py
- tests/backends/apsw/dialects/test_gsheets.py
This allows for simple authentication when running in an environment where app default credentials are enabled (e.g. Google Cloud Functions, Cloud Run, or on a local development machine where `gcloud auth application-default login` has been run).
> Add support for using Google Application Default Credentials for Google Sheets

- src/shillelagh/backends/apsw/dialects/base.py
- tests/backends/apsw/dialects/test_gsheets.py
The SQLite dialect in SQLAlchemy defines its own custom types to handle date/time/datetime stored as string, but Shillelagh already handles that. This PR removes those custom types from the Shillelagh base dialect to prevent SQLAlchemy from trying to double parse.
Closes https://github.com/betodealmeida/shillelagh/issues/193.
> fix: SQLAlchemy datetime types

- src/shillelagh/adapters/api/gsheets/adapter.py
- tests/adapters/api/gsheets/test_adapter.py
The fix we had for sheets were the first row is not detected correctly as the column names (https://github.com/betodealmeida/shillelagh/commit/24f939923196a37415cfb5a753fc5955768e5fa9) was buggy — it would add an offset of 1 to the query, which only works for `SELECT *`.
This PR fixes the problem by setting `headers=1` on the URL.
> fix: offset bug in gsheets

- docs/development.rst
- src/shillelagh/adapters/api/weatherapi.py
- src/shillelagh/adapters/base.py
- src/shillelagh/adapters/file/csvfile.py
- src/shillelagh/backends/apsw/vt.py
Closes: https://github.com/betodealmeida/shillelagh/issues/227
Per https://github.com/rogerbinns/apsw/blob/6913d52acbbb80b5a697d21817de744370ca72d2/src/vtable.c#L798-L804, the estimatedCost should be a double / `float`.
> Change retrn type of get_cost to be a float

- docs/development.rst
> Fix typo where insert_row was called insert_rows

- src/shillelagh/backends/apsw/vt.py
closes: https://github.com/betodealmeida/shillelagh/issues/216
> Read off sqlite constants from apsw

- src/shillelagh/backends/apsw/db.py
- tests/backends/apsw/dialects/test_base.py
- tests/backends/apsw/test_db.py
Closes: https://github.com/betodealmeida/shillelagh/issues/217
> Fix description returned in the case of empty set

- Makefile
- src/shillelagh/backends/apsw/db.py
- src/shillelagh/backends/apsw/dialects/gsheets.py
- src/shillelagh/backends/apsw/vt.py
- src/shillelagh/fields.py
- tests/adapters/api/test_datasette.py
- tests/adapters/file/test_csvfile.py
- tests/backends/apsw/dialects/test_gsheets.py
- tests/backends/apsw/test_vt.py
Fix `do_ping` in the GSheets dialect, the `incidents.json` had no entries for "Google Sheets" resulting in an error.
Also fix some lint and code coverage.
```bash
% make test
% make check
```
> fix(gsheets): `do_ping`

- .github/workflows/python-package-daily.yml
- .github/workflows/python-package.yml
- setup.cfg
The 3.10 daily tests were failing because of an old version of `setuptools`, and because PyPI only has `apsw` version 3.9.2 for Python 3.10, which raises a `SystemError` This PR changes the actions to upgrade both.
> fix: 3.10 daily tests

- AUTHORS.rst
- src/shillelagh/backends/apsw/vt.py
Previously when there was a column that only had one quotation mark it would fail to upload the sheet, this add a quotation mark to it which escapes out of the quotation mark.
> chore: new logic for escaping quotes

- tests/adapters/api/gsheets/test_integration.py
Add integration tests querying https://docs.google.com/spreadsheets/d/1_rN3lm0R_bU3NemO0s9pbFkY5LQPcuy1pscv8ZXPtg8/edit#gid=767615647.
> test: add integration test for quoted col names

- .pre-commit-config.yaml
- src/shillelagh/adapters/api/gsheets/adapter.py
- src/shillelagh/backends/apsw/vt.py
- src/shillelagh/exceptions.py
- tests/adapters/api/gsheets/test_adapter.py
- tests/adapters/api/gsheets/test_integration.py
Raise a custom exception when we try to connect to a protected sheet.
This will allow us to capture the exception in Superset, send the user to authorize, store the user token, and use it in subsequent requests.
Added tests.
> feat (gsheets): raise custom auth exception

- src/shillelagh/adapters/api/gsheets/parsing/number.py
- tests/adapters/api/gsheets/parsing/test_number.py
When parsing a number, if we can't apply the pattern provided by GSheets we fallback to int/float.
Updated unit tests.
> fix: lenient number parser

- .pylintrc
- src/shillelagh/adapters/api/datasette.py
- src/shillelagh/adapters/api/github.py
- src/shillelagh/adapters/api/gsheets/adapter.py
- src/shillelagh/adapters/api/s3select.py
- src/shillelagh/adapters/api/socrata.py
- src/shillelagh/adapters/api/system.py
- src/shillelagh/adapters/api/weatherapi.py
- src/shillelagh/adapters/file/csvfile.py
- src/shillelagh/lib.py
- tests/adapters/api/datasette_test.py
- tests/adapters/api/github_test.py
- tests/adapters/api/socrata_test.py
- tests/adapters/api/system_test.py
- tests/adapters/base_test.py
- tests/fakes/__init__.py
- tests/lib_test.py
Add support for limit/offset to all adapters except for WeatherAPI.
Still need to update developer docs, will do that in a separate PR.
> feat: implement limit/offset in adapters

- ARCHITECTURE.rst
- README.rst
- src/shillelagh/adapters/api/github.py
- src/shillelagh/adapters/api/socrata.py
- src/shillelagh/fields.py
- tests/fields_test.py
Use standard library functions to parse ISO in the `ISO*` fields (`ISODate`, `ISODateTime`, `ISOTime`).
Also add new custom fields that are more permissive, for APIs that return formats that can't be parsed with `fromisoformat` (eg, GitHub returns timestamps as strings with `Z` for the timezone, which is not supported by `datetime.fromisoformat`).
Closes #220.
Closes #221.
> chore: use fromisoformat

- src/shillelagh/fields.py
- tests/fields_test.py
Add support for polymorphic fields.
Closes #211
I added a test implementing a polymorphic field.
> feat: support for polymorphic fields

- CHANGELOG.rst
- src/shillelagh/backends/apsw/dialects/base.py
Before running an update SQLAlchemy with run a `SELECT` statement to get the number of rows about to be modified. After running the update it compares the number of rows from the `SELECT` with the `rowcount` returned by the `UPDATE` query. For `apsw` the row count is zero, so the update fails.
This PR sets `supports_sane_rowcount` to false in the base dialect, so that SQLAlchemy skips the row check.
> chore: set supports_sane_rowcount

- src/shillelagh/backends/apsw/vt.py
- src/shillelagh/fields.py
- tests/fields_test.py
Create a `FastISODateTime` field for SQLite serialization/deserialization, and make the `ISODateTime` field use `dateutil.parser.isoparse` so it works with any valid ISO 8601 values.
> chore: improve datetime parsers

- docs/adapters.rst
Fixes #290 
The code is formatted in black.
Since this is a documentation revision, I would like to leave it to GitHub Actions to run tests.
I expect to pass.
> fix(docs): SyntaxError in catalog parameter

- src/shillelagh/adapters/file/csvfile.py
- src/shillelagh/typing.py
- tests/adapters/api/gsheets/integration_test.py
- tests/adapters/file/csvfile_test.py
- tests/backends/apsw/dialects/gsheets_test.py
Add support for remote CSV files (accessible via HTTP or HTTPS). Eg:
```sql
SELECT * FROM "https://example.com/test.csv";
```
In the future we should refactor the HTTP(S) part into a base class for all the file-based adapters, decoupling the transport from the format.
I added unit tests.
> feat: support remote CSV files

- src/shillelagh/adapters/api/gsheets/parsing/number.py
- tests/adapters/api/gsheets/parsing/number_test.py
Fix a bug in the GSheets adapter where the number "1.001" was being incorrectly parsed as "1.1". This was happening because when parsing the fractional part `001` with the `get_fraction` we were getting `0.1` instead of `0.001`. I fixed the logic in `get_fraction`.
Updated unit tests and added tests covering the bug.
> fix (gsheets): fraction parsing

- src/shillelagh/adapters/api/gsheets/parsing/number.py
- tests/adapters/api/gsheets/parsing/number_test.py
Fix for GSheets where this was not true:
```python
assert parse_number_pattern("-$12.2", "$#0.0,,") == -12200000.0
```
Added tests.
> fix (gsheets): handle negative case

- CHANGELOG.rst
- src/shillelagh/adapters/registry.py
- tests/adapters/registry_test.py
The adapter registry was trying to load adapters even if they were not explicitly requested, which could break in case some optional dependencies were missing.
Added unit test.
> fix: don't load non-requested adapters

- examples/generic_json.py
- src/shillelagh/adapters/api/generic_json.py
- tests/adapters/api/generic_json_test.py
Improve the generic JSON adapter, adding error handling and flattening or recursive values.
Also add an example of using the adapter.
```
$ shillelagh
sql> SELECT * FROM "https://api.domainsdb.info/v1/domains/search?domain=facebook&zone=com#$.domains[*]";
```
> chore: improve generic JSON adapter

- CHANGELOG.rst
- src/shillelagh/lib.py
- tests/lib_test.py
> fix: support booleans on type inferral

- src/shillelagh/adapters/memory/pandas.py
- tests/adapters/memory/pandas_test.py
> fix: handle dataframes without column names

- ARCHITECTURE.rst
- src/shillelagh/lib.py
- tests/adapters/api/gsheets/adapter_test.py
- tests/lib_test.py
Use `marshal` instead of `pickle` when serializing arguments to adapters.
A user reported an error where one of the arguments being passed was a custom class, and it caused an error during deserialization. I think it's safe to be strict here and enforce that arguments are basic types.
Now when the serialization fails we get an error message explaining the problem.
Added unit test.
> feat: stricter serialization

- CHANGELOG.rst
- src/shillelagh/adapters/api/s3select.py
- tests/adapters/api/s3select_test.py
If credentials are not passed explicitly to `s3_select`, use those in the environment.
Added tests.
> feat (s3_select): use available credentials

- CHANGELOG.rst
- docs/adapters.rst
- src/shillelagh/adapters/api/generic_json.py
- tests/adapters/api/generic_json_test.py
- tests/adapters/api/socrata_test.py
Allow specifying custom request headers when using the generic JSON adapter.
Closes https://github.com/betodealmeida/shillelagh/issues/335.
> feat (generic JSON): request headers

- src/shillelagh/backends/apsw/db.py
- src/shillelagh/lib.py
- tests/lib_test.py
Fixes #338 
When virtual tables were added/created, they were incorrectly escaped. 
This adds a new escape method for table identifier (as suggested in the linked issue) and renames the old one.
Added unit tests for the new identifier escape method.
> fix: Add separate method to escape identifiers correctly when creating virtual tables.

- CHANGELOG.rst
- docs/development.rst
- examples/generic_json.py
- requirements/base.txt
- requirements/test.txt
- setup.cfg
- src/shillelagh/adapters/api/generic_json.py
- src/shillelagh/adapters/base.py
- src/shillelagh/backends/apsw/db.py
- src/shillelagh/backends/apsw/vt.py
- tests/backends/apsw/db_test.py
- tests/backends/apsw/vt_test.py
Initial support for https://github.com/betodealmeida/shillelagh/issues/344. I'll add estimated rows in a separate PR.
Closes https://github.com/betodealmeida/shillelagh/issues/293
Added unit tests.
> feat: support best index

- CHANGELOG.rst
- src/shillelagh/adapters/registry.py
- tests/adapters/registry_test.py
- tests/backends/apsw/db_test.py
Closes https://github.com/betodealmeida/shillelagh/issues/341.
Updated unit tests.
> fix: error loading adapters

- src/shillelagh/backends/apsw/vt.py
- tests/backends/apsw/vt_test.py
See https://github.com/betodealmeida/shillelagh/issues/344#issuecomment-1499717353.
> fix: BestIndexObject index

- CHANGELOG.rst
- examples/dataframe.py
- src/shillelagh/adapters/memory/pandas.py
- tests/adapters/memory/pandas_test.py
Fix for empty dataframe, closes https://github.com/betodealmeida/shillelagh/issues/349.
> fix: empty dataframes

- CHANGELOG.rst
- docs/adapters.rst
- requirements/test.txt
- setup.cfg
- src/shillelagh/adapters/api/generic_json.py
- tests/adapters/api/generic_json_test.py
Allow passing request headers in the generic JSON adapter as query parameters, see https://github.com/betodealmeida/shillelagh/pull/337#issuecomment-1512007720.
> feat(generic JSON): pass request headers as query parameters

- CHANGELOG.rst
- src/shillelagh/adapters/registry.py
- tests/adapters/registry_test.py
> chore: only warn if adapter was specified

- requirements/base.txt
- requirements/test.txt
- setup.cfg
- src/shillelagh/adapters/registry.py
- src/shillelagh/functions.py
- tests/functions_test.py
pkg_resources is in the process of being deprecated in favor of
importlib.metadata and importlib.resources
importlib.metadata has been available in the standard library since 3.8
And as of 3.10 the importlib.metadata API is no longer provisional
In order to support Python version older than 3.10, the
`importlib_metadata` backport is used instead of the actual
`importlib.metadata` API.
(NOTE: There was no explicit install_require entry that needed removing
in setup.py for the setuptools package which provides the pkg_resources
module. It seems that it was merely assumed that setuptools is always
present, which is actually not the case.)
> refactor: pkg_resources -> importlib.metadata

- src/shillelagh/adapters/api/system.py
- tests/adapters/api/system_test.py
Improve the `system` adapter so we can get CPU and memory in a single query:
```
SELECT * FROM "system://";
```
And also make it support requested columns.
Updated unit tests.
> feat: combined system resource adapter

- CHANGELOG.rst
- src/shillelagh/adapters/api/gsheets/adapter.py
- src/shillelagh/adapters/api/gsheets/fields.py
- src/shillelagh/adapters/api/gsheets/lib.py
- src/shillelagh/adapters/api/gsheets/parsing/base.py
- src/shillelagh/adapters/api/gsheets/parsing/date.py
- src/shillelagh/adapters/file/csvfile.py
- tests/adapters/api/gsheets/adapter_test.py
- tests/adapters/api/gsheets/fields_test.py
- tests/adapters/api/gsheets/lib_test.py
- tests/adapters/api/gsheets/parsing/base_test.py
- tests/adapters/api/gsheets/parsing/date_test.py
- tests/adapters/api/gsheets/parsing/number_test.py
- tests/adapters/file/csvfile_test.py
- tests/lib_test.py
Allow querying durations in Google sheets. For example:
```
sql> SELECT * FROM "https://docs.google.com/spreadsheets/d/1LcWZMsdCl92g7nA-D6qGRqg1T5TiHyuKJUY1u9XAnsk/edit#gid=1648320094";
datetime               number  boolean    date        timeofday    string    duration
-------------------  --------  ---------  ----------  -----------  --------  ----------
2018-09-01 00:00:00         1  True       2018-01-01  17:00:00     test      0:11:00
2018-09-02 00:00:00         1  False                               test      0:12:00
2018-09-03 00:00:00         2  False                               test
2018-09-04 00:00:00         3  False                               test
2018-09-05 00:00:00         5  False                               test
2018-09-06 00:00:00         8  False …
```
> feat(gsheets): implement durations

- CHANGELOG.rst
- src/shillelagh/backends/apsw/vt.py
- tests/backends/apsw/vt_test.py
When an adapter doesn't support a given operator (say, `LIKE`) we were raising an exception. Instead, we can delegate to SQLite the work of doing the filtering by simply not raising the exception.
Fixes #376.
> fix: aggressive exception on missing operator

- CHANGELOG.rst
- src/shillelagh/adapters/api/gsheets/adapter.py
- src/shillelagh/console.py
- src/shillelagh/lib.py
- tests/adapters/api/gsheets/adapter_test.py
- tests/console_test.py
Introduce `NetworkAPICostModel`, which takes into consideration how much data is returned as the main cost factor.
> chore: better cost model for API adapters

- .coveragerc
- src/shillelagh/adapters/registry.py
- src/shillelagh/functions.py
- tests/adapters/base_test.py
- tests/functions_test.py
Tests in Python 3.10 and 3.11 are failing because we don't install `importlib-metadata` for those versions.
See https://github.com/betodealmeida/shillelagh/actions/runs/5909833386/job/16030813401.
> fix: importlib in tests

- CHANGELOG.rst
- src/shillelagh/adapters/api/datasette.py
- src/shillelagh/adapters/api/generic_json.py
- tests/adapters/api/datasette_test.py
- tests/adapters/api/generic_json_test.py
- tests/adapters/api/generic_xml_test.py
The `supports` method in the Datassette adapter was too aggressive. This PR modifies it to be more conservative.
Also fix the generic JSON adapter to handle null values.
> fix: datassette detection and JSON parsing

- setup.cfg
Installing just the CLI via `pip install 'shillelagh[console]'` results
in a non-function CLI, due to missing requests-cache third party libary.
fixes #400
> fix: No module named 'requests_cache'

- CHANGELOG.rst
- src/shillelagh/adapters/api/preset.py
- tests/adapters/api/preset_test.py
> fix: allow Preset handler to query workspaces

- CHANGELOG.rst
- src/shillelagh/adapters/api/generic_json.py
- src/shillelagh/adapters/api/preset.py
- tests/adapters/api/generic_json_test.py
- tests/adapters/api/generic_xml_test.py
- tests/adapters/api/preset_test.py
Allow passing a timeout in seconds to the JSON/XML/Preset adapters.
> feat: allow defining the cache timeout

- AUTHORS.rst
- src/shillelagh/adapters/api/gsheets/lib.py
- tests/adapters/api/gsheets/lib_test.py
`get_values_from_row` had a flaw that would result in a wrong value for `n_cols` under certain conditions. `n_cols` is expected to be the result of `get_index_from_letters` for the "highest letter" column. However, using `max` to get the "highest letter" column is not feasible as `max("Z", "AA") == "Z"`.
To fix this, `get_index_from_letters` is called on all values of `column_map` to make sure that we find the correct `n_cols`.
The unit test for `get_values_from_row` have been updated to cover this change as well.
> fix(gsheets): handle getting values from rows in wide tables

- CHANGELOG.rst
- requirements/test.txt
- setup.cfg
- src/shillelagh/adapters/api/generic_json.py
- src/shillelagh/adapters/api/github.py
- src/shillelagh/adapters/api/preset.py
- tests/adapters/api/generic_json_test.py
Use `python-jsonpath` instead of `jsonpath-python`, since it handles the root (`$`) better.
> fix: use better JSONPath library

- src/shillelagh/console.py
- tests/console_test.py
Improve the CLI:
- Introduce an `emit_statements` function, which takes lines and emit full SQL statements (handling quotes).
- Introduce a `repl` function, that handles the REPL prompt and emits SQL lines.
These two simplify the CLI loop tremendously:
```python
for query in emit_statements(repl(session)):
start = time.time()
results = None
try:
cursor.execute(query)
results = cursor.fetchall()
except Error as ex:
print(ex)
continue
headers = [t[0] for t in cursor.description or []]
print(tabulate(results, headers=headers))
duration = time.time() - start
print(
f"({len(results)} row{'s' if len(results) != 1 else ''} "
f"in {duration:.2f}s)\n",
)
connection.close()
print("GoodBye!")
```
And made it easy to introduce an TTY check so that we can call `shillelagh` in a pipe, in …
> feat: improve CLI

- .pre-commit-config.yaml
- CHANGELOG.rst
- setup.cfg
- src/shillelagh/adapters/api/gsheets/adapter.py
- src/shillelagh/adapters/api/gsheets/lib.py
- src/shillelagh/backends/apsw/dialects/gsheets.py
- tests/adapters/api/gsheets/adapter_test.py
> fix: Oauth2 in GSheets

- CHANGELOG.rst
- setup.cfg
In current Superset master, there is now a [bump](https://github.com/apache/superset/pull/27733) for ``tabulate`` from ``0.8.9`` to ``0.8.10``. Relaxing the required version since Superset 4.0 still doesn't depend on this bump.
> chore: relax tabulate dependency

- templates/adapter/cookiecutter.json
Fixes #441.
This makes the `adapter_type` in `cookiecutter.json` to lowercase so that it matches the adapter directory names and make the script `post_gen_project.sh` work.
```bash
$ git clone https://github.com/betodealmeida/shillelagh.git
$ cd shillelagh
$ python -m venv venv
$ source venv/bin/activate
$ python -m pip install cookiecutter
$ cookiecutter templates/adapter/
```
> fix(cookiecutter): adapter_type to lowercase

- src/shillelagh/backends/apsw/dialects/base.py
- fix(backends\apsw\dialects\base.py): prevent SADeprecationWarning: Add import_dbapi() to mimic dbapi() to prevent SADeprecationWarning
prevent SADeprecationWarning: Add import_dbapi() to mimic dbapi() to prevent SADeprecationWarning
What steps can be taken to manually verify the changes?
Install latest SQLAlchemy `pip install sqlalchemy` run the following code:
```Python
from sqlalchemy import create_engine, text
engine = create_engine(
"shillelagh://",
adapters=["csvfile"]
)
connection = engine.connect()
csv_file_path = "C:/Users/<user_name>/adaptor_test/test.csv"
query = text(f"SELECT * FROM '{csv_file_path}'")
try:
result = connection.execute(query)
for row in result:
print(row)
except Exception as e:
print(f"Error: {e}")
```
and observe warning:
```
SADeprecationWarning: The dbapi() …
```
> Add import_dbapi() to mimic dbapi() to prevent SADeprecationWarning

- src/shillelagh/adapters/api/gsheets/lib.py
- src/shillelagh/adapters/api/gsheets/parsing/base.py
- src/shillelagh/adapters/api/gsheets/parsing/date.py
- tests/adapters/api/gsheets/lib_test.py
- tests/adapters/api/gsheets/parsing/base_test.py
Handle incorrect API response from GSheets. Fixes #455.
> fix(GSheets): invalid pattern

- CHANGELOG.rst
- requirements/base.txt
- requirements/test.txt
- setup.cfg
- src/shillelagh/adapters/api/generic_json.py
- tests/adapters/api/generic_json_test.py
Handle array-only responses in the generic JSON adapter.
> feat(generic JSON): handle array-only responses

- CHANGELOG.rst
- src/shillelagh/adapters/api/generic_json.py
- tests/adapters/api/generic_json_test.py
> fix (generic JSON): handle arrays of strings

- src/shillelagh/backends/apsw/db.py
- src/shillelagh/functions.py
- tests/backends/apsw/db_test.py
- tests/functions_test.py
Allow upgrading Shillelagh from the process itself:
```sql
🍀> SELECT VERSION();
VERSION()
----------------------
1.2.25 (apsw 3.45.3.0)
(1 row in 0.00s)
🍀> SELECT UPGRADE("1.2.26");
UPGRADE("1.2.26")
-----------------------------
Upgrade to 1.2.26 successful.
(1 row in 0.76s)
🍀> SELECT VERSION();
VERSION()
----------------------
1.2.26 (apsw 3.45.3.0)
(1 row in 0.00s)
🍀>
```
> feat: upgrade lib from SQL

- CHANGELOG.rst
- docs/development.rst
- src/shillelagh/adapters/api/generic_json.py
- src/shillelagh/adapters/api/generic_xml.py
- src/shillelagh/adapters/api/preset.py
- tests/adapters/api/preset_test.py
Fix the Preset API pagination, removing `limit` and `offset`.
> fix: Preset API pagination

- src/shillelagh/fields.py
- tests/fields_test.py
This is used by the Apache Superset Meta Database connector:
https://github.com/apache/superset/blob/0fdcd8b27e6d6ba70f8f38b4a033c61555af92bd/superset/extensions/metadb.py#L157-L163
Adding it here because it makes sense to exist here.
> feat: Duration field

- .github/workflows/python-integration.yml
- .github/workflows/python-package-daily.yml
- .github/workflows/python-package.yml
- CHANGELOG.rst
- README.rst
- docs/postgres.rst
- examples/postgres.py
- postgres/Dockerfile
- requirements/test.in
- setup.cfg
I forgot I hadn't done a 1.3.0 release yet. 😄  PyPI complains about the git link for the `multicorn2` dependency, so I removed it and add instructions on how to run it manually.
> fix: release 1.3.0

- setup.cfg
Bump minimum apsw version to 3.43.2.0, when `createscalarfunction` [was renamed](https://rogerbinns.github.io/apsw/changes.html#renaming) to `create_scalar_function`.
Fixes https://github.com/betodealmeida/shillelagh/issues/487.
> chore: bump apsw dependency

- src/shillelagh/backends/apsw/db.py
- tests/backends/apsw/db_test.py
Fixes https://github.com/betodealmeida/shillelagh/issues/494.
> fix: NO_SUCH_TABLE regex

- .github/workflows/python-package.yml
- CHANGELOG.rst
- src/shillelagh/adapters/api/gsheets/adapter.py
- src/shillelagh/backends/apsw/dialects/gsheets.py
- tests/adapters/api/gsheets/adapter_test.py
- tests/backends/apsw/dialects/gsheets_test.py
> feat: allow passing SSL verify to session

- .pre-commit-config.yaml
- src/shillelagh/backends/apsw/dialects/gsheets.py
- tests/backends/apsw/dialects/gsheets_test.py
Fix how we build the credentials when calling `get_table_names` for the GSheets dialect.
Also fixes https://github.com/betodealmeida/shillelagh/issues/505.
> fix (gsheets): authenticated `get_table_names`

- src/shillelagh/adapters/api/gsheets/adapter.py
- src/shillelagh/adapters/api/gsheets/lib.py
- tests/adapters/api/gsheets/lib_test.py
Apparently the Google Charts API doesn't return strings sorted even if we ask for it.
Fixes https://github.com/betodealmeida/shillelagh/issues/506.
> fix(gsheets): order by

- src/shillelagh/adapters/api/gsheets/parsing/date.py
This small PR resolves the regex (`re`) library warnings:
```python
/home/runner/work/shillelagh/shillelagh/src/shillelagh/adapters/api/gsheets/parsing/date.py:185: DeprecationWarning: 'maxsplit' is passed as positional argument
/home/runner/work/shillelagh/shillelagh/src/shillelagh/adapters/api/gsheets/parsing/date.py:432: DeprecationWarning: 'maxsplit' is passed as positional argument
```
> Resolve regex library warnings

- setup.cfg
- src/shillelagh/adapters/api/dbt_metricflow.py
- src/shillelagh/backends/apsw/dialects/base.py
- src/shillelagh/backends/apsw/dialects/metricflow.py
- tests/adapters/api/dbt_metricflow_test.py
- tests/backends/apsw/dialects/metricflow_test.py
Add a SQLAlchemy dialect for MetricFlow, so it can be used with Apache Superset.
> feat: simple MetricFlow adapter+dialect for Superset
