src/shillelagh/adapters/api/gsheets.py
src/shillelagh/backends/apsw/db.py
src/shillelagh/fields.py
src/shillelagh/types.py
tests/adapters/api/test_gsheets.py
tests/adapters/api/test_weatherapi.py
tests/backends/apsw/test_db.py
tests/backends/apsw/test_dialect.py
tests/test_fields.py
tests/test_types.py

Handle native datetime objects when filtering and retrieving data.

Native datetime

---

src/shillelagh/adapters/file/csvfile.py

By the time `Disconnect` calls `close()` on the adapter the Python GC has already run and `open` is not longer available (!) to do GC on the CSV file.
I fixed this by registering the `close()` method to run on exit.

fix: GC on CSVFile

---

src/shillelagh/adapters/api/gsheets.py
tests/adapters/api/test_gsheets.py

Implement `update_data`, saving 1 network request and preventing the sheet rows to move.

feat: update_data for GSheets

---

src/shillelagh/backends/apsw/db.py
tests/backends/apsw/test_db.py

A few improvements to safe mode:
1. Adapters must be listed explicitly (in non-safe mode all adapters are used if none are specified).
2. Check for adapters with the same name, to prevent someone from sneaking a malicious adapter in a 3rd party dependency.

fix: improve safe mode

---

src/shillelagh/adapters/api/gsheets.py
tests/adapters/api/test_gsheets.py

Instead of using `filter_data` to filter local data when we have pending changes in GSheets, we can simply modify the columns and return all data so that SQLite does the filtering for us.

feat: make GSheets use SQLite for local queries

---

src/shillelagh/adapters/api/gsheets.py
src/shillelagh/adapters/api/socrata.py
src/shillelagh/adapters/api/weatherapi.py
src/shillelagh/adapters/base.py
src/shillelagh/adapters/file/csvfile.py
src/shillelagh/backends/apsw/db.py
src/shillelagh/backends/apsw/dialects/base.py
src/shillelagh/backends/apsw/dialects/safe.py
src/shillelagh/functions.py
tests/backends/apsw/dialects/test_safe.py
tests/fakes/__init__.py

Pass the adapter `kwargs` to `supports`.
This will allow us to implement a catalog for GSheets.

feat: pass kwargs to supports

---

src/shillelagh/adapters/api/gsheets.py
tests/adapters/api/test_gsheets.py

This PR fixes sheets where there's a column in the middle of the document that is empty (or has no header).

fix: empty middle columns DML

---

src/shillelagh/adapters/api/gsheets/lib.py
src/shillelagh/adapters/base.py
src/shillelagh/backends/apsw/db.py
src/shillelagh/backends/apsw/dialects/gsheets.py
src/shillelagh/lib.py
tox.ini

Closes https://github.com/betodealmeida/shillelagh/issues/67.

chore: check doctests

---

.cirrus.yml
.github/workflows/python-integration.yml
.github/workflows/python-package.yml
setup.cfg
src/shillelagh/adapters/api/gsheets/adapter.py
src/shillelagh/adapters/api/gsheets/lib.py
src/shillelagh/adapters/api/weatherapi.py
src/shillelagh/adapters/base.py
src/shillelagh/backends/apsw/vt.py
src/shillelagh/fields.py
tests/adapters/api/gsheets/test_adapter.py
tests/adapters/api/gsheets/test_integration.py
tests/adapters/api/gsheets/test_lib.py
tests/adapters/api/test_socrata.py
tests/adapters/api/test_weatherapi.py
tests/conftest.py
tox.ini

Add integration tests via https://pypi.org/project/pytest-integration/. To run the tests without integration tests:
```bash
pytest --cov=src/shillelagh -vv tests/ --doctest-modules src/shillelagh --without-integration --without-slow-integration
```
Closes https://github.com/betodealmeida/shillelagh/issues/81.

feat: add integration tests and fix some bugs

---

README.rst
docs/adapters.rst
examples/dataframe.py
setup.cfg
src/shillelagh/adapters/memory/pandas.py
tests/adapters/memory/test_pandas.py

Add a simple adapter for Pandas.
Given this dataframe:
```python
import pandas as pd
mydf = pd.DataFrame(
[
{"index": 10, "temperature": 15.2, "site": "Diamond_St"},
{"index": 11, "temperature": 13.1, "site": "Blacktail_Loop"},
{"index": 12, "temperature": 13.3, "site": "Platinum_St"},
{"index": 13, "temperature": 12.1, "site": "Kodiak_Trail"},
],
)
```
We can query it:
```python
from shillelagh.backends.apsw.db import connect
connection = connect(":memory:")
cursor = connection.cursor()
sql = "SELECT * FROM mydf"
cursor.execute(sql)
assert cursor.fetchall() == [
(10, 15.2, "Diamond_St"),
(11, 13.1, "Blacktail_Loop"),
(12, 13.3, "Platinum_St"),
(13, 12.1, "Kodiak_Trail"),
]
sql = "SELECT * FROM mydf WHERE temperature > 10 AND temperature < 10"
cursor.execute(sql)
assert cursor.fetchall() …
```

feat: add a Pandas in-memory adapter

---

.pre-commit-config.yaml
CHANGELOG.rst
docs/adapters.rst
docs/development.rst
src/shillelagh/adapters/api/gsheets/adapter.py
src/shillelagh/adapters/api/socrata.py
src/shillelagh/adapters/api/weatherapi.py
src/shillelagh/adapters/base.py
src/shillelagh/adapters/file/csvfile.py
src/shillelagh/adapters/memory/pandas.py
src/shillelagh/backends/apsw/vt.py
src/shillelagh/lib.py
src/shillelagh/typing.py
tests/adapters/api/gsheets/test_adapter.py
tests/adapters/api/test_socrata.py
tests/adapters/api/test_weatherapi.py
tests/adapters/file/test_csvfile.py
tests/adapters/memory/test_pandas.py

Closes https://github.com/betodealmeida/shillelagh/issues/68.

feat: estimate cost of queries

---

src/shillelagh/lib.py
tests/adapters/file/test_csvfile.py

Closes https://github.com/betodealmeida/shillelagh/issues/74.

fix: CSV adapter with 1 row of data

---

tests/adapters/api/gsheets/test_adapter.py
tests/adapters/api/gsheets/test_fields.py
tests/adapters/api/gsheets/test_lib.py
tests/adapters/api/test_socrata.py
tests/adapters/api/test_weatherapi.py
tests/adapters/file/test_csvfile.py
tests/adapters/test_base.py
tests/backends/apsw/dialects/test_base.py
tests/backends/apsw/dialects/test_gsheets.py
tests/backends/apsw/dialects/test_safe.py
tests/backends/apsw/test_db.py
tests/backends/apsw/test_vt.py
tests/fakes/__init__.py
tests/test_console.py
tests/test_fields.py
tests/test_filters.py
tests/test_functions.py
tests/test_lib.py
tests/test_types.py

Lint all the tests.
Closes https://github.com/betodealmeida/shillelagh/issues/72.

chore: lint tests

---

Makefile
docs/development.rst
src/shillelagh/adapters/api/datasette.py
src/shillelagh/adapters/api/gsheets/adapter.py
src/shillelagh/adapters/api/socrata.py
src/shillelagh/adapters/api/weatherapi.py
src/shillelagh/adapters/base.py
src/shillelagh/adapters/file/csvfile.py
src/shillelagh/adapters/memory/pandas.py
src/shillelagh/backends/apsw/db.py
src/shillelagh/backends/apsw/dialects/base.py
src/shillelagh/functions.py
src/shillelagh/lib.py
tests/fakes/__init__.py
tests/test_lib.py

Closes https://github.com/betodealmeida/shillelagh/issues/111.

feat: implement maybe in `supports`

---

CHANGELOG.rst
src/shillelagh/backends/apsw/dialects/base.py
tests/backends/apsw/dialects/test_base.py

Fixes https://github.com/betodealmeida/shillelagh/issues/112.

feat: add has_table

---

CHANGELOG.rst
src/shillelagh/adapters/api/gsheets/fields.py
src/shillelagh/adapters/api/gsheets/parsing/base.py
src/shillelagh/adapters/api/gsheets/parsing/pattern.py
src/shillelagh/adapters/api/gsheets/pattern.py
tests/adapters/api/gsheets/parsing/test_pattern.py
tests/adapters/api/gsheets/test_fields.py
tests/adapters/api/gsheets/test_integration.py
tests/adapters/api/gsheets/test_pattern.py
tests/adapters/api/test_socrata.py

This PR implements a parser/formatter for all the patterns used by the GSheets API (https://developers.google.com/sheets/api/guides/formats?hl=en).

feat: patter parser/formatter for GSheets

---

tests/adapters/api/test_datasette.py

Closes https://github.com/betodealmeida/shillelagh/issues/121.

chore (Datasette): integration test

---

.pre-commit-config.yaml
Makefile
templates/adapter/cookiecutter.json
templates/adapter/hooks/post_gen_project.sh
templates/adapter/{{cookiecutter.slug}}/test_{{cookiecutter.slug}}.py
templates/adapter/{{cookiecutter.slug}}/{{cookiecutter.slug}}.py

Template for creating new adapters:
```bash
% cd shillelagh
% cookiecutter templates/adapter
```
Closes https://github.com/betodealmeida/shillelagh/issues/126.

feat: cookiecutter template for adapters

---

CHANGELOG.rst
src/shillelagh/backends/apsw/vt.py
src/shillelagh/fields.py
tests/test_fields.py

feat: add duration field

---

src/shillelagh/adapters/api/github.py
tests/adapters/api/test_github.py
tests/adapters/api/test_socrata.py

This PR adds authentication to the GitHub adapter, and also fixes a bug where only open PRs were being returned when state was not specified.

feat: improvements to GitHub adapter

---

CHANGELOG.rst
README.rst
docs/adapters.rst
setup.cfg
src/shillelagh/adapters/api/system.py
src/shillelagh/backends/apsw/db.py
tests/adapters/api/test_system.py

A fun adapter:
```sql
sql> SELECT "timestamp", cpu0 FROM "system://cpu?interval=2" LIMIT 5;
timestamp                           cpu0
--------------------------------  ------
2021-12-23 18:13:01.022531+00:00   0.204
2021-12-23 18:13:03.027534+00:00   0.13
2021-12-23 18:13:05.030486+00:00   0.134
2021-12-23 18:13:07.034610+00:00   0.125
2021-12-23 18:13:09.038377+00:00   0.165
sql>
```

feat: system adapter

---

src/shillelagh/backends/apsw/dialects/base.py
src/shillelagh/backends/apsw/dialects/gsheets.py
src/shillelagh/backends/apsw/dialects/safe.py

Closes https://github.com/betodealmeida/shillelagh/issues/182.

feat: enable supports_statement_cache

---

AUTHORS.rst
src/shillelagh/adapters/api/gsheets/fields.py
src/shillelagh/fields.py
tests/test_fields.py

To remove dependency on distutils as suggested in #203.

Implement distutils.strtobool in class fields.StringBoolean

---

src/shillelagh/console.py
tests/test_console.py

chore: small fixes

---

CHANGELOG.rst

release: 1.0.11

---

CHANGELOG.rst

chore: 1.0.12

---

CHANGELOG.rst

chore: 1.0.13 release

---

CONTRIBUTING.rst

docs: developer docs

---

CHANGELOG.rst

chore: 1.0.14 release

---

AUTHORS.rst

Add Alex Rothberg to AUTHORS.rst in ordering based on first commit

---

src/shillelagh/adapters/api/gsheets/adapter.py

Address https://github.com/betodealmeida/shillelagh/pull/250#discussion_r888583282.

fix (gsheets): raise from exception

---

CHANGELOG.rst

chore: release 1.0.15

---

src/shillelagh/adapters/api/s3select.py
src/shillelagh/backends/apsw/db.py
src/shillelagh/backends/apsw/vt.py
src/shillelagh/lib.py
tests/adapters/api/gsheets/test_adapter.py
tests/adapters/api/test_weatherapi.py
tests/adapters/file/test_csvfile.py
tests/test_lib.py

Change the serialization/deserialization of adapter parameters, so we can pass more than strings.

chore: improve serialization

---

.github/workflows/python-package-daily.yml
.github/workflows/python-package.yml
setup.cfg

fix: testing deps was missing boto3

---

.github/workflows/python-package-daily.yml

chore: allow running action manually

---

CHANGELOG.rst
README.rst
docs/adapters.rst
src/shillelagh/adapters/api/s3select.py
tests/adapters/api/test_s3select.py

chore: update docs

---

.readthedocs.yml

> Error
> 
> Problem in your project's configuration. Invalid "python.version": expected one of (2, 2.7, 3, 3.5, 3.6, 3.7, 3.8, pypy3.5), got 3.9

fix: readthedocs

---

.readthedocs.yml

fix: readthedocs deps

---

src/shillelagh/adapters/api/html_table.py
src/shillelagh/adapters/memory/pandas.py

chore: consolidate some Pandas logic

---

requirements/base.txt
requirements/test.txt

chore: bump deps

---

setup.cfg

Closes https://github.com/betodealmeida/shillelagh/issues/144.

chore: add obsoletes

---

.pylintrc
CHANGELOG.rst
docs/usage.rst
src/shillelagh/adapters/api/gsheets/parsing/date.py
src/shillelagh/adapters/base.py
src/shillelagh/adapters/registry.py
src/shillelagh/backends/apsw/db.py
src/shillelagh/fields.py
src/shillelagh/lib.py
tests/adapters/api/gsheets/test_adapter.py
tests/adapters/api/test_weatherapi.py
tests/adapters/file/test_csvfile.py
tests/adapters/registry_test.py
tests/adapters/test_base.py
tests/backends/apsw/dialects/test_base.py
tests/backends/apsw/test_db.py
tests/conftest.py
tests/test_functions.py
tests/test_lib.py

Closes https://github.com/betodealmeida/shillelagh/issues/181.

feat: add adapter registry

---

examples/dataframe.py
src/shillelagh/adapters/api/datasette.py
src/shillelagh/adapters/api/github.py
src/shillelagh/adapters/api/gsheets/adapter.py
src/shillelagh/adapters/api/html_table.py
src/shillelagh/adapters/api/s3select.py
src/shillelagh/adapters/api/socrata.py
src/shillelagh/adapters/api/system.py
src/shillelagh/adapters/api/weatherapi.py
src/shillelagh/adapters/base.py
src/shillelagh/adapters/file/csvfile.py
src/shillelagh/adapters/memory/pandas.py
src/shillelagh/backends/apsw/vt.py
src/shillelagh/filters.py
tests/backends/apsw/vt_test.py
tests/fakes/__init__.py

Closes https://github.com/betodealmeida/shillelagh/issues/223.

feat: add support for limit/offset

---

ARCHITECTURE.rst
CHANGELOG.rst
Makefile
README.rst
docs/development.rst
docs/install.rst
setup.cfg

Add docs describing architecture.
Closes https://github.com/betodealmeida/shillelagh/issues/272
Closes https://github.com/betodealmeida/shillelagh/issues/252

docs: architecture

---

docs/development.rst
src/shillelagh/fields.py

docs: clarify custom fields

---

src/shillelagh/fields.py
src/shillelagh/filters.py

chore: use Collection instead of List

---

docs/development.rst
src/shillelagh/backends/apsw/dialects/base.py
src/shillelagh/backends/apsw/dialects/gsheets.py

Docs on how to create a new SQLAlchemy dialect.
Closes #188.

docs: creating new dialects

---

src/shillelagh/fields.py
tests/fields_test.py

chore: relax internal typevar

---

CHANGELOG.rst

chore: update CHANGELOG

---

CHANGELOG.rst
src/shillelagh/console.py
tests/console_test.py

fix: config directory

---

.github/workflows/python-package-daily.yml

fix: 3.11 version

---

.github/workflows/python-package-daily.yml

Python 3.11 was released today. Adding it to the nightly tests so we know when it can be supported.

chore: Python 3.11

---

CHANGELOG.rst

chore: release 1.1.1

---

src/shillelagh/adapters/api/gsheets/parsing/number.py

fix (gsheets): improve exception handling

---

CHANGELOG.rst

chore: release 1.1.2

---

README.rst

fix: README

---

.github/workflows/python-package.yml
.pre-commit-config.yaml
src/shillelagh/adapters/api/gsheets/parsing/date.py
src/shillelagh/adapters/api/gsheets/parsing/number.py
src/shillelagh/backends/apsw/db.py
tests/adapters/api/gsheets/fields_test.py
tests/adapters/api/gsheets/parsing/date_test.py
tests/adapters/file/csvfile_test.py
tests/fields_test.py

chore: run lint tests on CI

---

CHANGELOG.rst

chore: release 1.1.3

---

docs/development.rst
src/shillelagh/adapters/api/generic_json.py
src/shillelagh/adapters/api/s3select.py
src/shillelagh/lib.py
tests/adapters/api/generic_json_test.py
tests/adapters/api/s3select_test.py

Add some small fixes and improvements:
- handle nested JSON in the S3 select adapter
- return row ID in the s3 generic JSON adapter

chore: small fixes and improvements

---

CHANGELOG.rst
src/shillelagh/adapters/api/s3select.py
src/shillelagh/adapters/base.py
src/shillelagh/lib.py
tests/lib_test.py

Add proper JSON support to the S3 Select adapter.

chore: proper JSON support in S3 Select

---

src/shillelagh/backends/apsw/db.py

Ignore unknown keys in `shillelagh.yaml`.

chore: ignore uknown adapter kwargs

---

CHANGELOG.rst
requirements/test.txt
setup.cfg

chore: release 1.1.4

---

src/shillelagh/adapters/api/generic_json.py
src/shillelagh/adapters/api/s3select.py
src/shillelagh/adapters/api/socrata.py
src/shillelagh/adapters/file/csvfile.py
src/shillelagh/lib.py

Add a helper function to flatten rows that have JSON.

feat: helper to flatten nested rows

---

CHANGELOG.rst

chore: release 1.1.5

---

.coveragerc
src/shillelagh/backends/apsw/db.py
tests/backends/apsw/db_test.py

Allow specifying the name of the main schema (defaults to `main`).

feat: allow picking the main schema name

---

.pre-commit-config.yaml
CHANGELOG.rst
src/shillelagh/backends/apsw/dialects/base.py
src/shillelagh/backends/apsw/dialects/gsheets.py
tests/backends/apsw/dialects/base_test.py
tests/backends/apsw/dialects/gsheets_test.py

Adding support to SQLAlchemy 2.0.

chore: support SQLAlchemy 2.0

---

docs/development.rst

chore: update docs re: SQLAlchemy 2.0

---

docs/adapters.rst

fix(gsheets): the example in the doc is not correct

Fix typo for the adapter

---

.github/workflows/python-package.yml
CHANGELOG.rst
CONTRIBUTING.rst
examples/weatherapi.py
requirements/base.txt
requirements/test.txt
setup.cfg
src/shillelagh/adapters/api/gsheets/parsing/base.py
src/shillelagh/adapters/api/gsheets/parsing/date.py
src/shillelagh/adapters/api/gsheets/parsing/number.py
src/shillelagh/adapters/api/weatherapi.py
src/shillelagh/adapters/file/csvfile.py
src/shillelagh/backends/apsw/dialects/gsheets.py
src/shillelagh/backends/apsw/vt.py
src/shillelagh/filters.py
src/shillelagh/lib.py
tests/fakes/__init__.py
tests/fields_test.py

chore: support 3.11

---

CHANGELOG.rst

chore: release 1.2.1

---

CHANGELOG.rst

chore: release 1.2.3

---

CHANGELOG.rst
setup.cfg

fix(generic JSON): add yarl dependency

---

CHANGELOG.rst
setup.cfg

chore: relax requests-cache

---

src/shillelagh/backends/apsw/db.py
src/shillelagh/backends/apsw/vt.py
src/shillelagh/lib.py
src/shillelagh/typing.py
tests/adapters/base_test.py
tests/backends/apsw/db_test.py
tests/backends/apsw/vt_test.py
tests/fakes/__init__.py

Pass `requested_columns` in the serialized index.

feat: pass `requested_columns` in index

---

requirements/base.txt
requirements/test.txt
setup.cfg

Set a new minimum requests version to avoid https://github.com/advisories/GHSA-j8r2-6x86-q33q

chore: remove duplicate requests deps and bump ver

---

src/shillelagh/adapters/api/system.py
tests/adapters/api/system_test.py

Allow the system adapter to query memory and swap usage.

feat(system): memory and swap queries

---

CHANGELOG.rst

chore: release 1.2.5

---

CHANGELOG.rst
src/shillelagh/adapters/api/gsheets/fields.py
tests/adapters/api/gsheets/fields_test.py

Empty strings in GSheets should be encoded as `''`.
Closes #377.

fix(gsheets): empty strings

---

CHANGELOG.rst

chore: release 1.2.7

---

.pre-commit-config.yaml
setup.py

chore: add pyupgrade hook

---

.github/workflows/python-package-daily.yml
.github/workflows/python-package.yml

Add Python 3.12 to the CI pipelines.

chore: Python 3.12 in CI

---

.readthedocs.yml

fix: read the docs

---

CHANGELOG.rst

release: 1.2.8

---

.github/workflows/python-package-daily.yml
.github/workflows/python-package.yml
src/shillelagh/adapters/api/datasette.py
tests/adapters/api/datasette_test.py

fix: unit test

---

.github/workflows/python-publish.yml

chore: fix publish action

---

CHANGELOG.rst
README.rst
docs/install.rst
requirements/base.txt
setup.cfg

fix: add missing dependency

---

CHANGELOG.rst
docs/adapters.rst
docs/development.rst
templates/adapter/{{cookiecutter.slug}}/{{cookiecutter.slug}}.py
tests/adapters/api/generic_json_test.py

chore: update the cookiecutter template

---

templates/adapter/{{cookiecutter.slug}}/{{cookiecutter.slug}}.py

chore: improve comments in template

---

CHANGELOG.rst
examples/preset.py
setup.cfg
src/shillelagh/adapters/api/preset.py
tests/adapters/api/preset_test.py

feat: Preset API handler

---

CHANGELOG.rst

chore: release 1.2.13

---

CHANGELOG.rst

chore: release 1.2.14

---

CHANGELOG.rst
docs/adapters.rst
examples/preset.py
setup.cfg
src/shillelagh/adapters/api/preset.py
tests/adapters/api/preset_test.py

Optimize the [Preset API](https://api-docs.preset.io/#0ff76fbd-6a99-43db-bb0b-055246a893e7) adapters to handle pagination, limit, and offset.

feat(preset): improvements to handler

---

CHANGELOG.rst
docs/adapters.rst

chore: 1.2.17 release

---

CHANGELOG.rst

chore: release 1.2.18

---

CHANGELOG.rst
setup.cfg

chore: release 1.2.19

---

src/shillelagh/adapters/api/github.py
tests/adapters/api/github_test.py

Fixes https://github.com/betodealmeida/shillelagh/issues/449.

fix: remove GitHub limit/offset

---

CHANGELOG.rst

chore: release 1.2.20

---

CHANGELOG.rst

chore: release 1.2.21

---

CHANGELOG.rst

chore: release 1.2.22

---

CHANGELOG.rst
setup.cfg

chore: relax packaging dependency

---

CHANGELOG.rst

chore: release 1.2.27

---

README.rst

fix: links in README

---

CHANGELOG.rst

chore: release 1.3.0

---

CHANGELOG.rst
setup.cfg

chore: release 1.3.1

---

.github/workflows/python-package.yml

See https://turso.tech/blog/simple-trick-to-save-environment-and-money-when-using-github-actions.

chore: cancel stale tasks in CI

---

setup.cfg

fix: python_requires

---

.github/workflows/python-package-daily.yml

fix: install multicorn2 for daily tests

---

AUTHORS.rst

chore: update author list

---

src/shillelagh/backends/apsw/db.py
tests/adapters/memory/holidays_test.py
tests/backends/apsw/db_test.py
tests/console_test.py

Update tests to work with latest dependencies.

fix: update tests for latest dependencies

---

CHANGELOG.rst

chore: release 1.3.3

---

src/shillelagh/backends/apsw/db.py
tests/backends/apsw/db_test.py

This is a better approach, since `NO_SUCH_TABLE` has be used with `.search`, not `.match`. The function encapsulates that logic.

chore: implement `get_missing_table`

---

.gitattributes
talks/Designated Driver Episode #5 • Shillelagh.mkv

Add Designated Driver podcast where I talk about Shillelagh.

Add Designated Driver podcast

---

CHANGELOG.rst

chore: release 1.3.4

---

CHANGELOG.rst

chore: release 1.3.5

---

CHANGELOG.rst
src/shillelagh/backends/apsw/db.py
src/shillelagh/typing.py
tests/backends/apsw/db_test.py

feat: types in alias

---

CHANGELOG.rst

chore: release 1.3.6

---

docs/index.rst
docs/postgres.rst
docs/sqlglot.rst
src/shillelagh/backends/sqlglot/db.py

chore: sqlglot docs

---

tests/console_test.py

fix: tests that rely on timing

---

src/shillelagh/functions.py
tests/functions_test.py

Fixes https://github.com/betodealmeida/shillelagh/issues/473

feat: alternative upgrade methods

---

src/shillelagh/adapters/api/gsheets/adapter.py
src/shillelagh/backends/apsw/vt.py
tests/adapters/api/generic_json_test.py
tests/adapters/api/gsheets/adapter_test.py
tests/backends/apsw/vt_test.py

fix: segfault
